datamodule:
  data_root: "data"
  train_root: "data/train"
  val_root: "data/val"
  test_root: "data/test"
  batch_size: ${oc.env:batch_size, 16}
  num_workers: 4
  num_samples: -1
  mask:
    type: random
    acceleration: 4
  