trainer:
  gpus: 1
  log_every_n_steps: 10
  accelerator: cpu
  MLFLOW_TRACKING_URI: 'file:/Users/mohamedzeyad/Desktop/fastmri_knee/mlruns'
  TRAIN_RESULTS_FILE: ${oc.env:TRAIN_RESULTS_FILE, ""}
  EVAL_RESULTS_FILE: ${oc.env:EVAL_RESULTS_FILE, ""}
  run_id: ${oc.env:run_id, ""}
  PREDICTIONS_DIR: ${oc.env:PREDICTIONS_DIR, data/outputs/${trainer.run_id}/}

  train:
    experiment_name: ${oc.env:experiment_name, fastmri}
    max_epochs: ${oc.decode:${oc.env:max_epochs, 10}}
    strategy: auto
    results_fp: ""
    metric: psnr
    lr: 1e-3
    weight_decay: 1e-6
    batch_size: ${oc.decode:${oc.env:batch_size, 16}}
    optimizer_name: Adam

  eval:
    data_path: ${oc.env:eval_data_path, ./data/val}
  
  tune:
    n_trials: 10
    timeout: 7200  # in seconds

  predict:
    data_path: ./data/test

  stop_on_first_improvement:
    enabled: ${oc.decode:${oc.env:stop_on_first_improvement, false}}
    monitor: ${trainer.checkpoint.monitor}
    mode: ${trainer.checkpoint.mode}
    min_delta: 0.0

  early_stopping:
    monitor: ${trainer.checkpoint.monitor}
    mode: ${trainer.checkpoint.mode}
    patience: 0
    min_delta: 0.0

  checkpoint:
    path: ./mlflow_artifacts/checkpoints
    filename: UnetModel-ep{epoch:02d}
    n_epochs: 1
    top_k: 1
    monitor: psnr
    mode: max