trainer:
  gpus: 1
  log_every_n_steps: 10
  accelerator: gpu
  MLFLOW_TRACKING_URI: 'file:/Users/mohamedzeyad/Desktop/fastmri/mlruns'
  MLFLOW_SAVE_DIR: ./mlflow_artifacts

  train:
    experiment_name: ${oc.env:experiment_name, "fastmri"}
    max_epochs: ${oc.env.max_epochs, 10}
    strategy: auto
    results_fp: ""
    metric: psnr
    lr: 1e-3
    weight_decay: 1e-6
    batch_size: ${oc.env.batch_size, 16}
    optimizer_name: Adam

  tune:
    n_trials: 10
    timeout: 7200  # in seconds

  predict:
    batch:
      data_path: ./data/val

  checkpoint:
    path: ./mlflow_artifacts/checkpoints
    filename: UnetModel-ep{epoch:02d}
    n_epochs: 1
    top_k: 1
    monitor: psnr
    mode: max