
FROM nvcr.io/nvidia/tritonserver:24.05-py3

# Copy models into container
COPY ../../../triton_models /models

# Copy pyproject.toml and optional poetry.lock or requirements.txt
COPY pyproject.toml /app/

# Install dependencies from pyproject.toml
RUN pip install --upgrade pip \
    && pip install .

# Expose Triton’s default HTTP and gRPC ports
EXPOSE 8000 8001 8002

CMD ["tritonserver", "--model-repository=/models"]